import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createOrderMailer,orderEmail,defaultOrderRecipients} from '../order-email.js';
const order={id:'AT-test',mode:'payment',status:'pending',createdAt:'2026-09-29T00:00:00Z',recipient:{name:'테스트 고객'},items:[{name:'머그컵',option:'올라운드 인쇄',quantity:10,unitPrice:15000}],amount:150000};
function database(){const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE order_email_notifications(order_id TEXT PRIMARY KEY,payload TEXT,state TEXT,claim_token TEXT,first_attempt_at TEXT,last_attempt_at TEXT,provider_id TEXT,sent_at TEXT,error TEXT)");return db;}
const env={RESEND_API_KEY:'test-only',ORDER_EMAIL_FROM:'Goodsflap <orders@example.com>',PUBLIC_URL:'https://www.artell.co.kr'};
test('주문 접수 메일은 네이버 두 주소에 결제 대기와 상품 수량을 명시한다',()=>{const mail=orderEmail(order,{from:env.ORDER_EMAIL_FROM,to:defaultOrderRecipients,url:env.PUBLIC_URL});assert.deepEqual(mail.to,['buf28@naver.com','annova@naver.com']);assert.match(mail.subject,/결제 대기/);assert.match(mail.text,/올라운드 인쇄 \/ 10개/);assert.match(mail.text,/150,000원/);assert.match(orderEmail({...order,mode:'demo'},{to:[],url:'',from:''}).subject,/시연 주문/);});
test('미설정 시 주문 알림을 보관하고 연결 후 원래 내용으로 한 번만 보낸다',async()=>{const db=database();let calls=0;try{const before=createOrderMailer({db,env:{},fetcher:()=>{throw Error('must not send')}});assert.equal((await before.safeSend(order)).state,'pending');const sender=createOrderMailer({db,env,fetcher:async(url,options)=>{calls++;assert.equal(url,'https://api.resend.com/emails');assert.equal(JSON.parse(options.body).from,env.ORDER_EMAIL_FROM);return new Response(JSON.stringify({id:'mail-1'}));}});assert.equal((await sender.safeSend(order)).state,'sent');await sender.safeSend(order);assert.equal(calls,1);}finally{db.close();}});
test('발송 실패는 주문 흐름으로 예외를 넘기지 않고 같은 키와 본문으로 재시도한다',async()=>{const db=database();const requests=[];try{const sender=createOrderMailer({db,env,fetcher:async(url,options)=>{requests.push(options);if(requests.length===1)throw Error('network');return new Response(JSON.stringify({id:'mail-2'}));}});assert.equal((await sender.safeSend(order)).state,'failed');assert.equal((await sender.safeSend({...order,amount:1})).state,'sent');assert.equal(requests[0].headers['Idempotency-Key'],requests[1].headers['Idempotency-Key']);assert.equal(requests[0].body,requests[1].body);}finally{db.close();}});
test('동시 재시도는 한 번만 전송하고 오래된 미확인 건은 자동 중복 발송하지 않는다',async()=>{const db=database();let calls=0;try{const sender=createOrderMailer({db,env,fetcher:async()=>{calls++;await new Promise(r=>setTimeout(r,10));return new Response(JSON.stringify({id:'mail-3'}));}});await Promise.all([sender.safeSend(order),sender.safeSend(order)]);assert.equal(calls,1);db.prepare("UPDATE order_email_notifications SET state='failed',first_attempt_at=?").run('2020-01-01T00:00:00Z');assert.equal((await sender.safeSend(order)).state,'review');assert.equal(calls,1);}finally{db.close();}});

test('Gmail SMTP는 네이버 두 수신자 접수 여부를 확인하고 성공 건을 중복 발송하지 않는다',async()=>{const db=database();let calls=0;try{const sender=createOrderMailer({db,env:{SMTP_USER:'sender@gmail.com',SMTP_PASS:'test'},smtpFactory:()=>({sendMail:async payload=>{calls++;assert.equal(payload.from,'Goodsflap <sender@gmail.com>');assert.deepEqual(payload.to,defaultOrderRecipients);return {accepted:defaultOrderRecipients,rejected:[],messageId:'smtp-ok'};},close(){}})});assert.equal((await sender.safeSend(order)).state,'sent');await sender.safeSend(order);assert.equal(calls,1);}finally{db.close();}});
test('SMTP 일부 수신 실패나 응답 불명확 시 중복 발송 대신 확인 필요로 남긴다',async()=>{const db=database();let calls=0;try{const sender=createOrderMailer({db,env:{SMTP_USER:'sender@gmail.com',SMTP_PASS:'test'},smtpFactory:()=>({sendMail:async()=>{calls++;return {accepted:[defaultOrderRecipients[0]],rejected:[defaultOrderRecipients[1]]};},close(){}})});assert.equal((await sender.safeSend(order)).state,'review');assert.equal((await sender.safeSend(order)).state,'review');assert.equal((await sender.list())[0].state,'review');assert.equal(calls,1);}finally{db.close();}});
